title: "The Whitestone Foundation"
tagline: "Fostering critical thought for the public interest."
url: "http://localhost:8080/"
noindex: false
defaultLanguage: "en"
languages:
  en:
    contentDir: "content/"
    locale: "en-US"
    languageName: "English"
    title: "The Whitestone Foundation"
    tagline: "Fostering critical thought for the public interest."
head:
  link:
    - rel: "stylesheet"
      href: "/assets/css/index.css"
    - rel: "icon"
      href: "/images/whitestone-logo.webp"
  script:
    - src: "/assets/js/index.js"
      defer: true
  meta:
    - name: "theme-color"
      content: "#caf0f8"
    - name: "color-scheme"
      content: "light"
seo:
  preserveQueryParams: false
  ogImage:
    url: "/images/whitestone-logo.webp"
    width: 1200
    height: 630
    alt: "The Whitestone Foundation"
  openGraph:
    type: "website"
  twitter:
    card: "summary_large_image"
